# Generated by Django 3.2.19 on 2023-06-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=5)),
                ('BRAND', models.CharField(max_length=50)),
            ],
        ),
    ]
