# Generated by Django 3.2.19 on 2023-06-19 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MYAPP', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=10)),
                ('date', models.DateField(max_length=10)),
                ('total', models.CharField(max_length=50)),
                ('PRODCUT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.product')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MYAPP.user')),
            ],
        ),
    ]
